version: '3.9'
services:
  front_usa:
    build: { context: ./frontend/usa, target: prod }
    container_name: front_usa
    env_file: ./frontend/usa/.env_prod
    restart: unless-stopped

  proxy_tienda_salchimonster_usa:
    image: nginx:1.27-alpine
    container_name: proxy
    ports: [ '80:80', '443:443' ]
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/proxy_params:/etc/nginx/proxy_params:ro
      - ./nginx/certbot/www:/var/www/certbot:ro
      - ./nginx/letsencrypt:/etc/letsencrypt:ro
    depends_on: [front_usa]
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/letsencrypt:/etc/letsencrypt
    entrypoint: sh
    command: -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet; sleep 12h & wait $!; done"
    restart: unless-stopped

