version: '3.9'
services:
  front_usa:
    build: { context: ./frontend/usa, target: prod }
    container_name: front_usa
    env_file: ./frontend/usa/.env_prod
    restart: unless-stopped

  proxy_t_salchi_usa:
    build: { context: ./nginx }
    container_name: proxy
    ports: [ '80:80', '443:443' ]
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
      - ./nginx/proxy_params:/etc/nginx/proxy_params:ro
      - ./nginx/certbot/www:/var/www/certbot:ro
      - ./nginx/letsencrypt:/etc/letsencrypt:ro
    depends_on: [front_usa]
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/letsencrypt:/etc/letsencrypt
    depends_on: [proxy_t_salchi_usa]
    entrypoint: sh
    command: -c "until certbot certonly --webroot -w /var/www/certbot -d usa.salchimonster.com --email \"andrew19f@gmail.com\" --agree-tos --no-eff-email ; do echo 'Retrying in 30s...'; sleep 30; done; echo 'Certs ready.'; trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet || true; sleep 12h; done"
    restart: unless-stopped

