version: '3.9'
services:
  front_usa:
    build: { context: ./frontend/usa, target: dev }
    container_name: front_usa
    volumes:
      - ./frontend/usa/app:/app
      - front_usa_node_modules:/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
    env_file: ./frontend/usa/.env
    command: npm run dev -- --host 0.0.0.0
    ports:
      - '5173:5173'
    restart: unless-stopped

  proxy:
    image: nginx:1.27-alpine
    container_name: t_salchi_usa_proxy_dev
    ports: [ '80:80' ]
    volumes:
      - ./nginx_dev/conf.d:/etc/nginx/conf.d:ro
      - ./nginx_dev/proxy_params:/etc/nginx/proxy_params:ro
    depends_on: [front_usa]
    restart: unless-stopped

volumes:
  front_usa_node_modules:
