FROM node:20-alpine AS base
WORKDIR /app

FROM base AS dev
COPY ./app/package*.json ./
RUN npm install
EXPOSE 5173
CMD ["npm","run","dev","--","--host","0.0.0.0","--port","5173"]

FROM base AS builder
COPY ./app/package*.json ./
RUN npm install
COPY ./app .
COPY .env_prod .env
RUN npm run build

FROM nginx:1.27-alpine AS prod
COPY --from=builder /app/dist /usr/share/nginx/html
CMD ["nginx","-g","daemon off;"]
